### ISSUE TITLE
Bug: additional language columns disappear on export

### ISSUE THREAD

**Issue by Razpudding** [sozialhelden/survey-editor#13]
Currently, when I upload an xls with multiple languages, only one of the languages gets exported. The suffixes of the labels and hints 'Dutch (nl)' seem to disappear from the column names as well. Hopefully this is a small change.
I've emailed some example files just in case.

**Comment by opyh** [comment]
I've deployed a fix that seems to fix the issue. @Razpudding Could you check that it actually works and close the issue if it does? :)

**Comment by Razpudding** [comment]
Yup, that seems to have done the trick! Thanks for the fix 🙏
